spring.application.name=demo

spring.ai.openai.api-key=SUA_CHAVE_API
spring.ai.openai.chat.options.model=openai/gpt-oss-20b
spring.ai.openai.base-url=https://api.groq.com/openai

spring.datasource.url=jdbc:postgresql://localhost:5432/orcamentodb
spring.datasource.username=postgres
spring.datasource.password=SUA_SENHA_DO_POSTGRES
spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true

spring.ai.openai.audio.transcription.options.model=whisper-large-v3
spring.ai.openai.audio.transcription.options.response-format=text
